MIN_POINT_RANGE = 0.2 # [m]
OUTLIER_RANGE_DIFF = 0.3 # [m]
MIN_LINE_LENGTH = 0.5 # [m]
MIN_LINE_POINTS = 9
MAX_SPLIT_POINT_DIST = 0.1 # [m]
RANGE_ERROR = 0.01 # [%]
BEARING_ERROR = 0.0001**2 # [rad^2]
